version: '3'

volumes:
  vendor-store:
  node_modules-store:

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
    - ./src/laravel:/var/www
    - vendor-store:/var/www/vendor
    - node_modules-store:/var/www/node_modules
    environment:
      TZ: Asia/Tokyo

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 8001:80
    volumes:
    - ./src/laravel:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: ccs
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pass
      MYSQL_ROOT_PASSWORD: root_pass
      
      TZ: 'Asia/Tokyo'
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 4306:3306